### ISSUE TITLE
Module smc_samplers: 'random_walk' or 'random walk'?

### ISSUE THREAD

**Issue by hai-dang-dau** [nchopin/particles#1]
In the module `smc_samplers.py`, at lines 383 and 477, the documentation says that `type_prop` is `random_walk`. However, at lines 364 and 366, the variable `type_prop` is set to or compared with `random walk` instead.

**Comment by nchopin** [comment]
I fixed the documentation: option should be "random walk", not "random_walk". The documentation now includes the docstring of the base class of SMC samplers, which defines the arguments of the __init__ of its subclasses. Thanks for spotting this!
