### ISSUE TITLE
Bug: numpy import missing in collectors.py

### ISSUE THREAD

**Issue by jorgemcgomes** [nchopin/particles#17]
numpy is used in the online smoother classes but it is not being imported in the module.

(sorry for not opening a PR, but the fix is trivial and I don't have the repo ready at hand)

**Comment by nchopin** [comment]
Hi,
seems to be fixed in in the experimental branch? see line 192:

import numpy as np

Aslo, I've just merged the experimental branch into the master branch a few minutes ago. 

Plz let me know I'm missing something.

**Comment by jorgemcgomes** [comment]
That's it. I was on master. Thanks.
