### ISSUE TITLE
multiSMC seeding does not work with scipy frozen distribution

### ISSUE THREAD

**Issue by hai-dang-dau** [nchopin/particles#19]
The code and its comments are self-explanatory. Try running it.

```python
import particles
import scipy.stats as st
import numpy as np

class MyFK(particles.FeynmanKac):
    def __init__(self):
        self.distribution_of_M0 = st.norm(loc=2, scale=3)

    def M0(self, N):
        res = self.distribution_of_M0.rvs(size=N)
        print(res)
        return res

    def M(self, t, xp):
        pass

    def logG(self, t, xp, x):
        return np.zeros(len(x))

    def done(self, smc):
        return smc.t >= 1

fk = MyFK()
pf = particles.multiSMC(nruns=2, nprocs=2, fk=fk, N=5)
# so, seeding done by `particles` has no effect ???

# What is surprising is that, in single core setting, scipy does indeed use numpy seeds
my_dist = st.norm(loc=2, scale=3)

np.random.seed(1234)
print(my_dist.rvs(size=5))

np.random.seed(1234)
print(my_dist.rvs(size=5)) # same as above
```

**Comment by nchopin** [comment]
Frozen distributions are evil... OK, I will close this issue when this point is properly documented somewhere in the package.

**Comment by AdrienCorenflos** [comment]
Just to comment on what Nicolas said, when freezing a scipy distribution,
you not only freeze the parameters, you also freeze the numpy random state
that came with it (see [this line](
https://github.com/scipy/scipy/blob/adc4f4f7bab120ccfab9383aba272954a0a12fb0/scipy/stats/_distn_infrastructure.py#L594)
in scipy source code).

So now how does that affect the multiprocessing? Fundamentally there are
two conflicting phenomena at stake here: global state and pickling. The way
numpy seeding works is by modifying a global object generator object (you
can find it under `np.random.mtrand._rand`). Now before forking new
processes and running the function you want to parallelize, multiprocessing
pickles the arguments, and at some point ends up pickling the global random
state registered within the distribution. When you now unpickle the
arguments in their respective processes, the reference to the global state
is lost and you end up having two states, one local to your distribution,
and the "new" global state that is specific to the process. Calling
np.random.seed changes the latter, and not the former, hence the observed
behaviour. This is probably more easily seen on the minimal example below:


```python
import multiprocessing
import numpy as np
import scipy.stats as st

loc = 0.
scale = 1.

my_dist = st.norm(loc, scale)

class seeder(object):
    def __init__(self, dist):
        self.dist = dist

    def __call__(self, seed):
        np.random.seed(seed)
        print("global seed:", np.random.get_state()[1][0])
        print("local seed:", self.dist.random_state.get_state()[1][0])
        return self.dist.rvs()

seeded_dist = seeder(my_dist)

np.random.seed(0)

seeds = [1, 2, 3, 4]
with multiprocessing.Pool(len(seeds)) as p:
    res = p.map(seeded_dist, seeds)

print(res)
```

Le sam. 6 juin 2020 à 15:12, Nicolas Chopin <notifications@github.com> a
écrit :

**Comment by nchopin** [comment]
This is now properly documented in module utils. However, a more general issue is to better deal with random states, multi-processing, and the recent improvements in numpy.random (since numpy 1.17).

**Comment by oneway3124** [comment]
results = particles.multiSMC(fk=fk_model, N=100, nruns=30, qmc={'SMC':False, 'SQMC':True})

C:\ProgramData\Anaconda3\envs\particles\lib\multiprocessing\popen_spawn_win32.py in __init__(self, process_obj)
     91             try:
     92                 reduction.dump(prep_data, to_child)
---> 93                 reduction.dump(process_obj, to_child)
     94             finally:
     95                 set_spawning_popen(None)

C:\ProgramData\Anaconda3\envs\particles\lib\multiprocessing\reduction.py in dump(obj, file, protocol)
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)
     61 
     62 #

PicklingError: Can't pickle <function _identity at 0x000002D7B4A67A60>: it's not the same object as particles.core._identity
