### ISSUE TITLE
Recognition of auxiliary filters

### ISSUE THREAD

**Issue by hai-dang-dau** [nchopin/particles#31]
File ``core.py``, lines 185-188, an auxiliary particle filter is recognised by testing the ``logetat`` attribute. However, in line 322, the attribute ``logeta`` of ``self.fk`` is called instead.

This could lead to APF ``FeynmanKac`` objects not being executed properly if they contain ``logeta`` attribute but not ``logetat``. This is the case for APF objects created via ``state_space_models.py``.

Seems like the correct fix is to put ``logeta`` at line 188 (in coherence with ``state_space_models.py``), but more testing might need to be done (e.g. existing codes).

**Comment by AdrienCorenflos** [comment]
Hi!
First of all, nice work on thw waste free SMC @hai-dang-dau !
On this, testing for behaviour based on the presence or absence of an attribute is an antipattern an can lead to issues as you highlighted. This should be handled by the inheritance contract, so the real thing to check is if self is an instance of APFMixin (or AuxiliaryPF, depending on logic). The way I would go around it is to delete the isAPF altogether and then replace its use by a direct isinstance check. For instance this
https://github.com/nchopin/particles/blob/8e5eb4c6886823598ba941d4f4eab551e8779509/particles/core.py#L311
would be replaced more cleanly by 
```python
if isinstance(self.fk, AuxiliaryPF):
```
if you are worried about circular imports, you can also use local imports of AuxiliaryPF

**Comment by hai-dang-dau** [comment]
@AdrienCorenflos Thanks for your feedback. I do not entirely agree with the type checking solution because that seems to go against Python's "duck typing" philosophy (i.e. any object with the ``logeta`` method should work with the implementation, regardless of its type).

My proposition would be to add a boolean-valued ``useAPF`` keyword argument in the SMC class. My arguments are:

(1) Even if a ``FeynmanKac`` object does include the ``logeta`` method, the user may, out of curiosity, prefers running the standard filter instead and sets ``useAPF=False``.

(2) If ``useAPF`` is set to ``True``, the implementation shall call ``fk.logeta`` without checking. So if the user passes in a ``FeynmanKac`` object without ``logeta`` method and sets ``useAPF=True``, an ``AttributeError`` is therefore automatically raised (which is what we want anyway).

**Comment by nchopin** [comment]
I applied the quick fix recommended by Dang. Now things should work as expected.
But it's true that the current design is a bit dodgy, as proved by this "silent bug". I'll think about it.
