### ISSUE TITLE
Bayesian inference for some parameters.

### ISSUE THREAD

**Issue by MaurusGubser** [nchopin/particles#34]
I have troubles with parameter estimation. I would like to use PMMH to get an estimate of some (but not all) of my models parameters. To begin, I tried that for the stochastic volalitility model from the basic tutorial. Instead of defining three priors for mu, sigma and rho, I only defined priors for mu and sigma and hand them over to the PMMH object:
```
prior_dict = {'mu':dists.Normal(),  'sigma': dists.Gamma(a=1., b=1.)}
my_prior = dists.StructDist(prior_dict)
pmmh = mcmc.PMMH(ssm_cls=StochVol, prior=my_prior, data=data, Nx=50, niter = 1000)
```
This only works, if I define `default parameters` for the `StochVol` model - at least for rho, for which I did not set up a prior.
```
class StochVol(ssm.StateSpaceModel):
    default_params = {'rho': 0.9}

    def PX0(self):  # Distribution of X_0
        return dists.Normal(loc=self.mu, scale=self.sigma / np.sqrt(1. - self.rho ** 2))

    def PX(self, t, xp):  # Distribution of X_t given X_{t-1}=xp (p=past)
        return dists.Normal(loc=self.mu + self.rho * (xp - self.mu), scale=self.sigma)

    def PY(self, t, xp, x):  # Distribution of Y_t given X_t=x (and possibly X_{t-1}=xp)
        return dists.Normal(loc=0., scale=np.exp(x))
```
For my model, I use an `__init__` constructor instead of `default_params`, since my model parameters are a bit more involved. I don't understand, how I can define priors for only some of my model parameters in that case. What I tried was something analogue to
```
pmmh = mcmc.PMMH(ssm_cls=StochVol(rho=0.9), prior=my_prior, data=data, Nx=50, niter = 1000)
```
but this fails, since PMMH expects a class, rather than an object.

My question is: Is it possible to hand over priors for some of the parameters without introducing default parameters? Or do I have to introduce default parameters?

**Comment by nchopin** [comment]
Why don't you just pass the class you have defined as the `ssm_cls` argument? 
```
pmmh = mcmc.PMMH(ssm_cls=StochVol, prior=my_prior, data=data, Nx=50, niter = 1000)
```

I assume you have defined the `__init__` method as something like:

```
class Stochvol(ssms.StateSpaceModel):
    def _init__(self, mu=0., sigma=0.1, rho=0.9):
        self.mu, self.sigma, self.rho = mu, rho, sigma
        # stuff
 
```

and then if you define a prior for mu and sigma, each time PMMH will instantiate the class, `rho` will be set to the default value you have defined in your __init__ function. 

Hope this helps, but, if not, feel free to post your class, so that I can better understand the issue.

**Comment by lawofearth** [comment]
> 
> 
> Why don't you just pass the class you have defined as the `ssm_cls` argument?
> 
> ```
> pmmh = mcmc.PMMH(ssm_cls=StochVol, prior=my_prior, data=data, Nx=50, niter = 1000)
> ```
> 
> I assume you have defined the `__init__` method as something like:
> 
> ```
> class Stochvol(ssms.StateSpaceModel):
>     def _init__(self, mu=0., sigma=0.1, rho=0.9):
>         self.mu, self.sigma, self.rho = mu, rho, sigma
>         # stuff
>  
> ```
> 
> and then if you define a prior for mu and sigma, each time PMMH will instantiate the class, `rho` will be set to the default value you have defined in your **init** function.
> 
> Hope this helps, but, if not, feel free to post your class, so that I can better understand the issue.

Is there any way to pass hyperparameters into the model without going to change `default_params` ? 

For example, if I would like to vary lag term of (p,q) in GARCH(p,q) model.

**Comment by nchopin** [comment]
Sorry, @lawofearth, I did not understand your question. 
`default_params` does only one thing: to provide default values for parameters. 
When you sub-class `StateSpaceModel` and **do not** define an `__init__` method, then you have the default behaviour where:
1.  parameters that you did not define are replaced by their default values;
2. "hyper-parameters" (meaning: parameters that are *not* in the signature of your sub-class) are simply ignored.   

If you decide to define your own ``__init__``, then `default_params` is ignored, and the behaviour you get is what you implement. For instance, if you do this:

```
class Stochvol(ssms.StateSpaceModel):
    def _init__(self, mu=0., sigma=0.1, rho=0.9):
        self.mu, self.sigma, self.rho = mu, rho, sigma
        # stuff
```
then you have behaviour 1 for parameters mu, rho, sigma, but not behaviour 2 above. But you could do something like:

 ```
class Stochvol(ssms.StateSpaceModel):
    def _init__(self, mu=0., sigma=0.1, rho=0.9, my_hyper_parameter=2.):
        self.mu, self.sigma, self.rho = mu, rho, sigma
        # stuff
```

where you explicitly name your hyper-parameter in the signature. In that case, you can set a prior for `my_hyper_parameter` and use e.g. PMMH. Each time a `StochVol` object is created, a value for the hyper-parameter is provided, even if that object is not going to do anything with it. 

And of course, you could do more fancy Python stuff, like: 

 ```
class Stochvol(ssms.StateSpaceModel):
    def _init__(self, mu=0., sigma=0.1, rho=0.9, **kwargs):
        self.mu, self.sigma, self.rho = mu, rho, sigma
        # stuff
```

where you can define later on whatever name for your hyper-parameter, and the class will not complain about a name it does not know. 

Does this anwser your question? If not, a MRU of what you are trying to do would help me to better understand it.

**Comment by lawofearth** [comment]
> 
> 
> Sorry, @lawofearth, I did not understand your question. `default_params` does only one thing: to provide default values for parameters. When you sub-class `StateSpaceModel` and **do not** define an `__init__` method, then you have the default behaviour where:
> 
>     1. parameters that you did not define are replaced by their default values;
> 
>     2. "hyper-parameters" (meaning: parameters that are _not_ in the signature of your sub-class) are simply ignored.
> 
> 
> If you decide to define your own `__init__`, then `default_params` is ignored, and the behaviour you get is what you implement. For instance, if you do this:
> 
> ```
> class Stochvol(ssms.StateSpaceModel):
>     def _init__(self, mu=0., sigma=0.1, rho=0.9):
>         self.mu, self.sigma, self.rho = mu, rho, sigma
>         # stuff
> ```
> 
> then you have behaviour 1 for parameters mu, rho, sigma, but not behaviour 2 above. But you could do something like:
> 
> ```
> class Stochvol(ssms.StateSpaceModel):
>    def _init__(self, mu=0., sigma=0.1, rho=0.9, my_hyper_parameter=2.):
>        self.mu, self.sigma, self.rho = mu, rho, sigma
>        # stuff
> ```
> 
> where you explicitly name your hyper-parameter in the signature. In that case, you can set a prior for `my_hyper_parameter` and use e.g. PMMH. Each time a `StochVol` object is created, a value for the hyper-parameter is provided, even if that object is not going to do anything with it.
> 
> And of course, you could do more fancy Python stuff, like:
> 
> ```
> class Stochvol(ssms.StateSpaceModel):
>    def _init__(self, mu=0., sigma=0.1, rho=0.9, **kwargs):
>        self.mu, self.sigma, self.rho = mu, rho, sigma
>        # stuff
> ```
> 
> where you can define later on whatever name for your hyper-parameter, and the class will not complain about a name it does not know.
> 
> Does this anwser your question? If not, a MRU of what you are trying to do would help me to better understand it.

Thank you, that answer my question.
