### ISSUE TITLE
Handling missing observations

### ISSUE THREAD

**Issue by MaurusGubser** [nchopin/particles#42]
I'm working with a two leg model of (human) motion. The model has a 18-dimensional state space:
- two dimensional position of hip
- four angles: vertical - left femur, left femur - left fibula, vertical - right femur, right femur - right fibula
- first and second derivatives of the above six quantities

The observation space is 36 dimensional:
- four IMUs at femur and fibula, left and right. Each IMU measures three linear accelerations and three angular velocities.
- two pressure sensors at the heel, left and right

While the measurements of the IMUs come fairly regularly, the pressure sensors provide no information as long as the corresponding foot has no floor contact. This means, I have to handle missing data, concretely, my `data` array contains NaNs.

I'm not sure, how to implement this. My first intuition was to handle two cases in the `PY` method:
```
def PY(self, t, xp, x):
    if data_is_complete:
        return dists.MvNormal(loc=self.state_to_observation(x), cov=self.H)
    else:
        return dists.MvNormal(loc=self.state_to_observation_restricted(x), cov=self.H)
```
However, at this level (when defining my state space model class), I don't have any information about my `data` to define the condition `data_is_complete`. In the `proposal` method, this is possible, because there, my `data` is accessible.

So far, my only solution is to include my `data` in the initialization of my `StateSpaceModel`, which is certainly not ideal. Also, I don't want to mess around in the `particle` code.

Is there a better way, how I can handle missing data?

Edit: I added the code for my proposal distribution. Since my distributions are multivariate Gaussian, I use an EKF for my proposal. Having available my `data` in the `proposal` method, I handle missing data the following way:
```
    def compute_ekf_proposal(self, xp, data_t):
        x_hat = self.state_transition(xp)
        df = self.compute_observation_derivatives(x_hat)

        innovation_inv = np.linalg.inv(np.matmul(df, np.matmul(self.Q, np.transpose(df, (0, 2, 1)))) + self.H)
        kalman_gain = np.matmul(self.Q, np.matmul(np.transpose(df, (0, 2, 1)), innovation_inv))
        prediction_err = np.nan_to_num(data_t - self.state_to_observation(x_hat), nan=0.0)

        mu = x_hat + np.einsum('ijk, ik -> ij', kalman_gain, prediction_err)
        sigma = np.matmul(np.eye(self.dim_states) - np.matmul(kalman_gain, df), self.Q)
        return mu, sigma

    def proposal(self, t, xp, data):
        mean, kalman_covs = self.compute_ekf_proposal(xp, data[t])
        covar = self.factor_proposal * np.mean(kalman_covs, axis=0)
        return dists.MvNormal(loc=mean, cov=covar)
```

**Comment by nchopin** [comment]
Hi,
first, did you see the new tutorial on defining "complex" state-space models? see [here](https://particles-sequential-monte-carlo-in-python.readthedocs.io/en/latest/notebooks/complicated_state_space_models.html). 

One point I make in this tutorial is that in some cases it might be easier to implement your Feynman-Kac model manually; e.g. in your case, the logG function could return different things according to whether y_t contains NaN or not. 

Alternatively, if you want to define a state-space model, you need to incorporate in the model the fact that some components are missing; say with probability p. To do so,  you may define custom probability distributions. Here is a very basic version: 

`from numpy import random

from particles import state_space_models as ssms
from particles import distributions as dist

```
class MixMissing(dist.ProbDist):
    """With prob 1/2, we get a Nan, otherwise, we get a draw from base
    distribution.
    """
    def __init__(self, base_dist=None):
        self.base_dist = base_dist

    def logpdf(self, x):
        if np.isnan(x):
            return 0.
        else:
            return self.base_dist.logpdf(x)
````
This is a bit of a hack:
* I did not define a rvs method (to sample from this distribution), as presumably don't need to sample from it. (Since this distribution for the data, the only case where you would use it is when using the simulate method of our ssm object.) 
* in case a Nan is observed, it returns a scalar; this is usually fine since if you add a scalar delta to a set of N weights, it does what you expect (each weight is incremented by delta), but there might be corner cases when this does not work (for instance at time 0?). The reason why I don't return a zero array is that there is no simple way to infer what is the output of base_dist.logpdf(x) (which would have the correct shape). 

Yet another option would be to adapt the code of GuidedPF, to make sure that logG returns a zero arrray at times t where the data is missing. BTW, You said you don't want to "mess with particles code", but you can always sub-class an existing class and override the  methods you want to change. Object orientation = efficient recycling of code.

Hope this helps. I am a bit tired since I taught 3 lectures today, so I might not make much sense. :-)

**Comment by MaurusGubser** [comment]
Thanks a lot for your answer, took my way too long to reply, sorry.  Don't worry about making sense, if I should also put some effort into understanding your answer :) I (now) also read the tutorial on defining complex SSMs, helped me for some stuff, but I wish I saw it earlier :)

Of course you are right with your remark that I can sub-class any existing class, I should have formulated that better. In fact, I solved the problem by subclassing the `MvNormal` class and defining my own `logpdf` method:

```
    def logpdf(self, x):
        mask_not_nan = np.invert(np.isnan(x))[0]
        loc_not_nan = self.loc[:, mask_not_nan]
        mask_2d = np.outer(mask_not_nan, mask_not_nan)
        nb_non_nan = np.sum(mask_not_nan)
        L_not_nan = np.reshape(self.L[mask_2d], (nb_non_nan, nb_non_nan))
        x_not_nan = x[:, mask_not_nan]

        z = solve_triangular(L_not_nan, np.transpose((x_not_nan - loc_not_nan) / self.scale), lower=True)
        # z is dxN, not Nxd
        if np.asarray(self.scale).ndim == 0:
            logdet = self.dim * np.log(self.scale)
        else:
            logdet = np.sum(np.log(self.scale), axis=-1)
        logdet += self.halflogdetcor
        return - 0.5 * np.sum(z * z, axis=0) - logdet - self.dim * HALFLOG2PI
```
But I'm not sure, if that's the way you suggested in your example. I only use this distribution in the `PY` method of my model, but I tried to keep it generic. If the input `x` is a state, no `NaN`s are detected and it should work just as `MvNormal`; if the input `x` is an observation, some components might be `NaN`s. But we still can use the `logpdf` method to compute weights, we compute them just using the observations we actually have.

I think, this is not quite the way, you described in your answer. In particular, with my idea, I sometimes compute the weights (coming from `PY`) using all observations (dimension 36) and sometimes only some observations (dimension 30 or even 24).

So far, this solved my problem with missing observations. But if you have any more remarks, I'm more than happy to hear them. :)

**Comment by nchopin** [comment]
OK, this is more or less what I had in mind. 
I think it would be nice to add a simple "missing obs" mechanism in the package, but it turns out to be a bit tricky. I'm going to let this issue open to try to come up with a solution.

**Comment by nchopin** [comment]
I have added some (limited) missing data functionality to the experimental branch; please have a look at:
* module distributions, in particular the new classes FlatNormal and MixMissing
* the general documentation of that module
* the examples in the new section at the end on the notebook on advanced state-space models. (You can't see it yet on readthedocs, as readthedocs tracks the master branch, but you can look directly at the notebook, it's in docs/source/notebooks)

This seems to work but may need more testing (and feedback)... :-)

**Comment by MaurusGubser** [comment]
Thank you for your work and the new implementations. I will try to test it. Although, I probably won't be able to do so before End of April or even begin of May. But I try to come back to it as soon as possible :)

**Comment by MaurusGubser** [comment]
Sorry, took me way longer to test your new implementation for handling missing data. Implementing was not a problem, however, the results were not as I expected them to be. I have missing data in every time step: either the pressure sensor of the left foot or the pressure sensor of the right foot is missing.

Implementation of `FlatNormal`:
```
def PY(self, t, xp, x):
    y_pred = self.state_to_observation(x)
    dists_1d = []

    for i in range(0, self.dim_observations):
        if i in self.idx_left and self.left_missing[i]:
            dists_1d.append(dists.FlatNormal(loc=y_pred[:, i]))
        elif i in self.idx_right and self.right_missing[i]:
            dists_1d.append(dists.FlatNormal(loc=y_pred[:, i]))
        else:
            dists_1d.append(dists.Normal(loc=y_pred[:, i], scale=self.H[i, i]))
    return dists.IndepProd(*dists_1d)
```
This did not really work for me: there are never any weights computed. The same happens, when I work with your toy model. If I simulate data and run a particle filter for it, as soon as there is missing data, no weights are computed anymore (changed missing days to Friday, such that in the beginning, no data is missing):
```
class ToyModelWithMissingData(ssms.StateSpaceModel):
    default_params = {'sigmaX': 1., 'sigmaY': 0.2}
    def PX0(self):
        return dists.Normal(scale=self.sigmaX)
    def PX(self, t, xp):
        return dists.Normal(loc=xp, scale=self.sigmaX)
    def PY(self, t, xp, x):
        if t % 7 == 5:  # Friday
            return dists.FlatNormal(loc=x)
        else:  # Other days
            return dists.Normal(loc=x, scale=self.sigmaY)

toymod = ToyModelWithMissingData()

x, y = toymod.simulate(20)
fk = ssms.Bootstrap(ssm=toymod, data=y)
alg = particles.SMC(fk=fk, N=100, ESSrmin=0.5, verbose=True)
alg.run()
```
I'm not sure, if that's the way you intended it to be. To me, it looks like the `logpdf` method of `FlatNormal` should return 0.0 weights, but instead returns `NaN`s:
```
def logpdf(self, x):
    # ensures proper shape/type
    return 0. * (x + self.loc)
```

Implementation of `MixedMissing`:
```
def PY(self, t, xp, x):
    y_pred = self.state_to_observation(x)
    dists_1d = []

    for i in range(0, self.dim_observations):
        if i in self.idx_left or i in self.idx_right:
            dists_1d.append(dists.MixMissing(pmiss=0.2, base_dist=dists.Normal(loc=y_pred[:, i], scale=self.H[i, i])))
        else:
            dists_1d.append(dists.Normal(loc=y_pred[:, i], scale=self.H[i, i]))
    return dists.IndepProd(*dists_1d)
```
This worked, however, I did not achieve results as good as with my own solution. So far, I do not understand, why the results are not as good as with my own solution, I need to investigate further.

One last remark: in the documentation, in the section **Missing at random times** you wrote:
_Note in particular how the ESS stays equals to 100 (the maximum value, since N=100) at times where a Nan was observed._
I guess, this is only true, if no resampling step was executed; if no resampling step is necessary and there are missing observations, the ESS stays the same, right?

...and thanks again for your implementation and your solution for handling missing observations. I hope, I can get my head around why my and your solution get different results.
