### ISSUE TITLE
Typos in `MvNormal`

### ISSUE THREAD

**Issue by MaurusGubser** [nchopin/particles#47]
https://github.com/nchopin/particles/blob/dd4ae7830f028c297c0cd5cad2635e97a90924cf/particles/distributions.py#L817-L818

I guess it should be `self.loc` in line 817 and  `np.matmul` in Line 818?

**Comment by nchopin** [comment]
Wow... So many mistakes in so few lines, my eyes hurt. :-)
On top of what you found, the formula for the posterior covariance matrix was wrong. 

It's a bit silly of me to implement these posterior methods, although I guess nobody use them. Anyway, the new version seems to work.
