### ISSUE TITLE
Wrong reference in documentation

### ISSUE THREAD

**Issue by MaurusGubser** [nchopin/particles#52]
Very minor issue: It seems to me that there is a wrong reference in the documentation, concretely in the "Advanced Tutorial" (https://particles-sequential-monte-carlo-in-python.readthedocs.io/en/latest/notebooks/advanced_tutorial_ssm.html) when talking about smoothing: At the very bottom of the page, readers are referenced to the book, chapter 11.6. I think this should be chapter 12.5, where the information filter and the two-filter smoother are explained.

**Comment by nchopin** [comment]
Thanks! Now fixed in both master and experimental, and readthedocs has been updated as well.
