### ISSUE TITLE
Fixed-lag smoothing crashes with QMC

### ISSUE THREAD

**Issue by jorgemcgomes** [nchopin/particles#7]
If store_history is an int, a history object of type RollingParticleHistory is created.
This object doesn't have the function save_h_order, which is called when qmc=True, causing a crash.

(ignore the line numbers, as I have other non-related modifications in core.py that affect them)
```
~/particles/particles/core.py in __next__(self)
    443             self.setup_auxiliary_weights()  # APF
    444             if self.qmc:
--> 445                 self.resample_move_qmc()
    446             else:
    447                 self.resample_move()

~/particles/particles/core.py in resample_move_qmc(self)
    407         h_order = hilbert.hilbert_sort(self.X)
    408         if self.hist:
--> 409             self.hist.save_h_order(h_order)
    410         self.A = h_order[rs.inverse_cdf(u[tau, 0], self.aux.W[h_order])]
    411         self.Xp = self.X[self.A]

AttributeError: 'RollingParticleHistory' object has no attribute 'save_h_order'
```

**Comment by jorgemcgomes** [comment]
Aside from this (which I circumvented with a hacky `if self.hist and isinstance(self.hist, smoothing.ParticleHistory)`), fixed-lag smoothing appears to be working fine. The performance appears to be similar to the fixed-lag smoothing method I had implemented before.

**Comment by nchopin** [comment]
thanks for spotting this! 
Now h-orders (order of the particles along the Hilbert curve) are saved only for full histories, which makes more sense. Also I took this opportunity to streamline the code a little bit.  

Are you already using the new collector for fixed-lag smoothing (option fixed-lag-smooth)?

**Comment by jorgemcgomes** [comment]
I only started testing the fixed-lag smoothing yesterday, so yes, I'm using the collector.
