### ISSUE TITLE
Mixture error?

### ISSUE THREAD

**Issue by austinTalbot7241993** [nchopin/particles#72]
I think line 793 should be 
self.k = self.pk.shape[-1]. 

Even if I'm wrong the following code makes this package unhappy

class MyModel(ssm.StateSpaceModel):
    def PX0(self):  
        return dists.Normal(loc=1.0, scale=0.1)
    def PX(self, t, xp):  
        return dists.Mixture([0.95,0.05],dists.Normal(loc=xp,scale=0.01),dists.Normal(loc=xp,scale=1.0))
    def PY(self, t, xp, x):  
        return dists.Normal(loc=x, scale=0.1)

model = MyModel()
true_states,data = model.simulate(100)

**Comment by nchopin** [comment]
Oops, sorry, fixed in experimental. Your piece of code should run ok now (if you switch to experimental branch). I'll propagate the change to master shortly.

**Comment by austinTalbot7241993** [comment]
Also I'm getting that backwards_sampling doesn't work in the advanced_tutorial_ssm of 

AttributeError: 'ParticleHistory' object has no attribute 'backward_sampling'

I assume this was a name change or something?

**Comment by nchopin** [comment]
> Also I'm getting that backwards_sampling doesn't work in the advanced_tutorial_ssm of
> 
> AttributeError: 'ParticleHistory' object has no attribute 'backward_sampling'
> 
> I assume this was a name change or something?

Also fixed now, thanks.
