### ISSUE TITLE
Feature request: parallelisation over the particles?

### ISSUE THREAD

**Issue by kpentland** [nchopin/particles#77]
Hi there, 

This is a great package, thanks for providing it! 

Having read the docs and parts of your book, I've been wanting to ask a question about the parallelisation of the your SMC routines. I see that it's possible to run multiple different (or the same) SMC simulations with 'multiSMC', however, is it possible to parallelise over the particles within a single run? For example, if I have $1000$ particles can I utilise $1000$ compute cores to parallelise over the particles? I notice you mention this briefly in your book (Chapter 19.2) but it is not discussed any further. Is this something that is possible to implement? I was thinking about having a go at implementing this myself but I thought I would ask first in case there was a reason it has not yet been tackled. 

For context, my application using 'Particles' is a state space model (with $\mathcal{O}(10^3)$ states), with many particles, and forward/measurement models that take $\mathcal{O}(10^1 - 10^2)$ seconds to run. Essentially I have a two-dimensional scalar field (where the spatial grid points each represent a state) to infer over time. Please do let me know if this is something that is possible or if I should perhaps be looking at another package or approach!

**Comment by nchopin** [comment]
Hi,
by default, the N particles are stored as a numpy array, of shape (N,) or (N, d). In that case, if you run a single SMC algorithm, *some* parallelisation over N may occur for free, that is, some of the numpy operations you do on this array may be performed automatically using all your cores; see e.g. here for more details:
https://roman-kh.github.io/numpy-multicore/
but in that case, I guess you won't get a x1000 speed-up with 1000 particles, even if you have 1000 cores. 

Note that I'm talking here about a **single** SMC run. Function `multiSMC` runs several SMC algorithms concurrently, but each algorithm is then attached to a single core. Parallelisation occurs across the runs, not across the particles for a single run.

I tried to implement the library in such a way that you may use any container/array types to represent the N particles (other than a numpy array), and I use that for SMC samplers (for a different reason). So, in principle, you could use some fancy library (dask?) that defines arrays for parallel computation on many cores? 
That's not something I really thought about. 
Another option (which is something I'd like to pursue in the near future) is to use a library for GPU computation (e.g. pytorch, jax), and then you would use say a torch device to represent your N particles, and makes sure all the computation occurs on the GPU.

**Comment by stijnhuysman** [comment]
Indeed, this is correct, 

first of all, thank you @Nicolas Chopin and your whole team for maintaining the particles packages. 
It makes your Book on Sequential MC complete and insightful ! 

Myself, I got confused first with the Feynman- Kac object that contains a specific model, but once you get used to it, it is very logical. 
While investigating an Statespace modeling approach, this multiSMC + FK framework is very simple to make some simulation 


My piece of code using the multiSMC below : 

import time 
start = time.time() 

#TO ME multiSMC, is used to perform multiple FK objects in one line of code. 

#THE CODE UNDERNEATH RUNS A SAMPLER WITH 3 feynman-Kac models, 2 runs for each, and with 3 different set of particles. 
# Optionally, the ESS can be given, as well as multiple resampling options 
# IN the case below, 3 * 2 * 3 = 18 combinations of particle filter models are run in parallell 
# according to the documentation, nprocs = 0 will use all available cores to do a parallell computation 

#From my experience, it is not possible to parallelize the set of particles at each run 

RESULT_SAMPLER = particles.multiSMC(fk = [ model_fk_object_1, model_fk_object_2, model_fk_object_3], 
nruns = 2 , 
N = [ 100 , 500 , 1000 ], 
nprocs = 0, 
store_history = False , 
ESSrmin = 0.5, 
collect = [Moments], 
resampling = [ 'systematic' ]) 

end = time.time() 


print ( " The time of execution of above program with ", len (RESULT_SAMPLER), " combinatons took :" , 
(end-start)/ 60 , "min" ) 


Van: "Nicolas Chopin" ***@***.***> 
Aan: "nchopin/particles" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Verzonden: Woensdag 6 december 2023 15:03:27 
Onderwerp: Re: [nchopin/particles] Feature request: parallelisation over the particles? (Issue #77) 





Hi, 
by default, the N particles are stored as a numpy array, of shape (N,) or (N, d). In that case, if you run a single SMC algorithm, some parallelisation over N may occur for free, that is, some of the numpy operations you do on this array may be performed automatically using all your cores; see e.g. here for more details: 
[ https://roman-kh.github.io/numpy-multicore/ | https://roman-kh.github.io/numpy-multicore/ ] 
but in that case, I guess you won't get a x1000 speed-up with 1000 particles, even if you have 1000 cores. 

Note that I'm talking here about a single SMC run. Function multiSMC runs several SMC algorithms concurrently, but each algorithm is then attached to a single core. Parallelisation occurs across the runs, not across the particles for a single run. 

I tried to implement the library in such a way that you may use any container/array types to represent the N particles (other than a numpy array), and I use that for SMC samplers (for a different reason). So, in principle, you could use some fancy library (dask?) that defines arrays for parallel computation on many cores? 
That's not something I really thought about. 
Another option (which is something I'd like to pursue in the near future) is to use a library for GPU computation (e.g. pytorch, jax), and then you would use say a torch device to represent your N particles, and makes sure all the computation occurs on the GPU.

**Comment by kpentland** [comment]
Hi,

Thank you for the comments - they make for some interesting thoughts!

I will also have a think about if there is a simple way to parallelise across the particles and will keep you posted on my progress. Using Dask, PyTorch, and/or Jax sound like sensible suggestions.
