### ISSUE TITLE
Sensor fusion - multiple `PY` depending on which sensor is returning

### ISSUE THREAD

**Issue by tsbertalan** [nchopin/particles#81]
I'd like to fuse multiple sensors with different noise characteristics. Is that possible with this library? That is, I have a common `PX` for my `StateSpaceModel`, but three different `PY` that have different heteroscedasticity, asymmetry, etc.

**Comment by nchopin** [comment]
I think so, but could you please clarify which scenario you have in mind? 
1. Are the three sensors observed simultaneously, at each time $t$, but they have a different distribution?  
2. Or do you observe a single sensor each time, but the sensor you observe varies across time? In which way, then? 
3. or some other scenario?

**Comment by tsbertalan** [comment]
The three sensors are coming in at different periods (say, 7 minutes, 1
minutes, 2 minutes), in general never near enough to the same times to be
bundled together as one higher-dim sensor. They are three differing
fidelity measurements of the same quantity with cost/delay of measurement
roughly correlated with fidelity.

I have created separate conditional sensor likelihood models for the three,
though this is currently just "calibrated" by my visual comparison to some
other plots of real data we have.

class Sensor:

    def __init__(self, delay_time=0.1, minval=0.0, maxval=12.0):
        self.minval = minval  # For truncated distributions.
        self.maxval = maxval
        self.delay_time = delay_time

    def __call__(self, true_conc):
        raise NotImplementedError
        return sample_distrubution, delay_time  # returns either a scipy
dist or a particles.distributions dist.

    def measure(self, true_conc):
        sample_distrubution, delay_time = self(true_conc)
        return sample_distrubution.rvs()

[image: image.png]

With these, I've created the following initial PF implementation (slightly
minified; I can put the whole thing in a pastebin if needed):

class MotionModel:
def __init__(self, k=0.5):
self.k = k
self.u = 0.0
def dXdt(self, t, X):
g, b = X
return [-self.k * g + self.u, self.k * g]
def sim_ufunc(self, t1, X1, t2, ufunc, **kwargs):
def rhs(t, X):
self.u = ufunc(t)
return self.dXdt(t, X)
return scipy.integrate.solve_ivp(rhs, (t1, t2), X1, **kwargs)
def flowmap(self, t1, X1, t2, u, **kwargs):
return self.sim_ufunc(t1, X1, t2, lambda t: u, **kwargs)
class Trajectory:
def __init__(self):
self.values = []
self.times = []
@property
def v(self):
return self.values[-1]
@property
def t(self):
return self.times[-1]
def update(self, t, v):
assert len(self.times) == 0 or t >= self.t
self.values.append(v)
self.times.append(t)
class Particle:
def __init__(self):
self.states = Trajectory()
self.weights = Trajectory()
@property
def state(self):
return self.states.v
@property
def weight(self):
return self.weights.v
@property
def t(self):
return max(self.states.t, self.weights.t)
def update(self, t, state=None, weight=None):
if state is not None:
self.states.update(t, state)
if weight is not None:
self.weights.update(t, weight)
def clone(self):
new_particle = Particle()
new_particle.update(self.t, state=self.state, weight=self.weight)
return new_particle
class ParticleFilter:
def __init__(self, N, initial_dist, motion_model, t=0, min_motion_step=.1,
motion_noise=.05, resampling_strategy=particles.resampling.systematic):
particle_values = initial_dist.rvs(N)
weight_values = np.ones(N).astype(float) / N
self.particles = []
for x, w in zip(particle_values, weight_values):
p = Particle()
p.update(t, state=x, weight=w)
self.particles.append(p)
self.lifetime_particles = list(self.particles)
self.motion_model = motion_model
self.t = t
self.min_motion_step = min_motion_step
self.motion_noise = motion_noise
self.means = Trajectory()
self.covs = Trajectory()
self.resampling_strategy = resampling_strategy
def maybe_predict(self, new_t, ufunc):
if new_t > self.t:
self.predict(new_t, ufunc)
def predict(self, new_t, ufunc):
assert new_t >= self.t
times_to_step = np.arange(self.t, new_t, self.min_motion_step)
if times_to_step[-1] < new_t:
times_to_step = np.concatenate([times_to_step, [new_t]])
estimation_groups = [[] for t in times_to_step[1:]]
for p in self.particles:
assert p.t == self.t
states = [p.state]
i = -1
for t_prev, t_next in zip(times_to_step[:-1], times_to_step[1:]):
i += 1
next_x = self.motion_model.sim_ufunc(t_prev, states[-1], t_next, ufunc).y[:,
-1]
next_x += np.random.normal(scale=self.motion_noise, size=next_x.shape)
states.append(next_x)
estimation_groups[i].append(next_x)
p.update(t_next, state=next_x)
assert p.t == new_t, (p.t, new_t)
self.t = new_t
w = np.array([p.weight for p in self.particles]).flat
for t, group in zip(times_to_step[1:], estimation_groups):
X = np.vstack(group)
mean = np.average(X, weights=w, axis=0)
cov = np.cov(X.T, aweights=w)
self.means.update(t, mean)
self.covs.update(t, cov)
def update(self, measurement):
"""measurement is a dictionary with fields
t
g_hat
sensor
"""
X = np.vstack([np.array(p.state).reshape((1, -1)) for p in self.particles])
W = np.array([p.weight for p in self.particles]).reshape((-1, 1))
p_y_given_x = np.array([
measurement['sensor'](x[0])[0].pdf(measurement['g_hat'])
for x in X
]).reshape((-1, 1))
W *= p_y_given_x
W /= W.sum()
for p, w in zip(self.particles, W):
p.update(self.t, weight=w)
def resample(self):
X = np.vstack([np.array(p.state).reshape((1, -1)) for p in self.particles])
W = np.array([p.weight for p in self.particles]).reshape((-1))
# indices = np.random.choice(len(self.particles), size=len(self.particles),
replace=True, p=W)
# Do the resampling with a scheme from particles.
indices = self.resampling_strategy(W)
new_particles = []
kept_once = []
for i in indices:
p = self.particles[i]
if p in kept_once:
# We've kept it once, now we must clone it.
p = p.clone()
# New particles get kept in the permanent history too, so they can be
plotted later even if they're dropped.
self.lifetime_particles.append(p)
else:
# If not, we'll make a note to do that next time.
kept_once.append(p)
# Regardless, this fresh or retained particle is to be put into the new
pool.
new_particles.append(p)
# Finally, use the new particles for our filtering going forward.
self.particles = new_particles
# And reweight them.
w = 1. / len(self.particles)
for p in self.particles:
p.update(t=self.t, weight=w)

[image: image.png]
It does ok, but probably mostly because the assumed motion model is nearly
the ground-truth.

Actually, The long delay until measurements are emitted may also be a
problem. I had anticipated having to manually keep some history around, and
then when a measurement comes in that was actually sampled in the past but
required 30 minutes for processing, I would go back in time and then apply
the measurements in sequence by their actual sampling times. But maybe
there's a hybrid smoothing/filtering approach that would handle this more
elegantly.

Finally, how *does *one actually apply this library online? All of the
examples show data being supplied all at once.

**Comment by tsbertalan** [comment]
(Re-posting the code and images since issues-by-email can't handle them.)

I have created separate conditional sensor likelihood models for the three,
though this is currently just "calibrated" by my visual comparison to some
other plots of real data we have.

```python
class Sensor:

    def __init__(self, delay_time=0.1, minval=0.0, maxval=12.0):
        self.minval = minval  # For truncated distributions.
        self.maxval = maxval
        self.delay_time = delay_time

    def __call__(self, true_conc):
        raise NotImplementedError
        return sample_distrubution, delay_time  # returns either a scipy
dist or a particles.distributions dist.

    def measure(self, true_conc):
        sample_distrubution, delay_time = self(true_conc)
        return sample_distrubution.rvs()
```
![image(1)](https://github.com/nchopin/particles/assets/306137/2ad09753-03f7-4270-8f95-aa20aadacf62)

With these, I've created the following initial PF implementation (slightly
minified; I can put the whole thing in a pastebin if needed):

```python
class MotionModel:
    def __init__(self, k=0.5):
        self.k = k
        self.u = 0.0
    def dXdt(self, t, X):
        g, b = X
        return [-self.k * g + self.u, self.k * g]
    def sim_ufunc(self, t1, X1, t2, ufunc, **kwargs):
        def rhs(t, X):
            self.u = ufunc(t)
            return self.dXdt(t, X)
        return scipy.integrate.solve_ivp(rhs, (t1, t2), X1, **kwargs)
    def flowmap(self, t1, X1, t2, u, **kwargs):
        return self.sim_ufunc(t1, X1, t2, lambda t: u, **kwargs)
class Trajectory:
    def __init__(self):
        self.values = []
        self.times = []
    @property
    def v(self):
        return self.values[-1]
    @property
    def t(self):
        return self.times[-1]
    def update(self, t, v):
        assert len(self.times) == 0 or t >= self.t
        self.values.append(v)
        self.times.append(t)
class Particle:
    def __init__(self):
        self.states = Trajectory()
        self.weights = Trajectory()
    @property
    def state(self):
        return self.states.v  
    @property
    def weight(self):
        return self.weights.v
    @property
    def t(self):
        return max(self.states.t, self.weights.t)
    def update(self, t, state=None, weight=None):
        if state is not None:
            self.states.update(t, state)
        if weight is not None:
            self.weights.update(t, weight)
    def clone(self):
        new_particle = Particle()
        new_particle.update(self.t, state=self.state, weight=self.weight)
        return new_particle
class ParticleFilter:
    def __init__(self, N, initial_dist, motion_model, t=0, min_motion_step=.1, motion_noise=.05, resampling_strategy=particles.resampling.systematic):
        particle_values = initial_dist.rvs(N)
        weight_values = np.ones(N).astype(float) / N
        self.particles = []
        for x, w in zip(particle_values, weight_values):
            p = Particle()
            p.update(t, state=x, weight=w)
            self.particles.append(p)
        self.lifetime_particles = list(self.particles)
        self.motion_model = motion_model
        self.t = t
        self.min_motion_step = min_motion_step
        self.motion_noise = motion_noise
        self.means = Trajectory()
        self.covs = Trajectory()
        self.resampling_strategy = resampling_strategy
    def maybe_predict(self, new_t, ufunc):
        if new_t > self.t:
            self.predict(new_t, ufunc)
    def predict(self, new_t, ufunc):
        assert new_t >= self.t
        times_to_step = np.arange(self.t, new_t, self.min_motion_step)
        if times_to_step[-1] < new_t:
            times_to_step = np.concatenate([times_to_step, [new_t]])
        estimation_groups = [[] for t in times_to_step[1:]]
        for p in self.particles:
            assert p.t == self.t
            states = [p.state]
            i = -1
            for t_prev, t_next in zip(times_to_step[:-1], times_to_step[1:]):
                i += 1
                next_x = self.motion_model.sim_ufunc(t_prev, states[-1], t_next, ufunc).y[:, -1]
                next_x += np.random.normal(scale=self.motion_noise, size=next_x.shape)
                states.append(next_x)
                estimation_groups[i].append(next_x)
                p.update(t_next, state=next_x)
            assert p.t == new_t, (p.t, new_t)
        self.t = new_t
        w = np.array([p.weight for p in self.particles]).flat
        for t, group in zip(times_to_step[1:], estimation_groups):
            X = np.vstack(group)
            mean = np.average(X, weights=w, axis=0)
            cov = np.cov(X.T, aweights=w)
            self.means.update(t, mean)
            self.covs.update(t, cov)
    def update(self, measurement):
        """measurement is a dictionary with fields
            t
            g_hat
            sensor
        """
        X = np.vstack([np.array(p.state).reshape((1, -1)) for p in self.particles])
        W = np.array([p.weight for p in self.particles]).reshape((-1, 1))
        p_y_given_x = np.array([
            measurement['sensor'](x[0])[0].pdf(measurement['g_hat'])
            for x in X
        ]).reshape((-1, 1))
        W *= p_y_given_x 
        W /= W.sum()
        for p, w in zip(self.particles, W):
            p.update(self.t, weight=w)
    def resample(self):
        X = np.vstack([np.array(p.state).reshape((1, -1)) for p in self.particles])
        W = np.array([p.weight for p in self.particles]).reshape((-1))
        # indices = np.random.choice(len(self.particles), size=len(self.particles), replace=True, p=W)
        # Do the resampling with a scheme from particles.
        indices = self.resampling_strategy(W)
        new_particles = []
        kept_once = []
        for i in indices:
            p = self.particles[i]
            if p in kept_once:
                # We've kept it once, now we must clone it.
                p = p.clone()
                # New particles get kept in the permanent history too, so they can be plotted later even if they're dropped.
                self.lifetime_particles.append(p)
            else:
                # If not, we'll make a note to do that next time.
                kept_once.append(p)
            # Regardless, this fresh or retained particle is to be put into the new pool.
            new_particles.append(p)
        # Finally, use the new particles for our filtering going forward.
        self.particles = new_particles
        # And reweight them.
        w = 1. / len(self.particles)
        for p in self.particles:
            p.update(t=self.t, weight=w)
```

![image](https://github.com/nchopin/particles/assets/306137/5ae9792b-c980-400f-a250-faba1474b2ea)

It does ok, but probably mostly because the assumed motion model is nearly
the ground-truth.

**Comment by nchopin** [comment]
Here is one way to deal with this situation: 

```
from particles import state_space_models as ssps
from particles import distributions as dists

def Foo(x):
    return dists.Norm(loc=x)

def Bar(x):
    return dists.gamma(loc=x)

class YourModel(ssps.StateSpaceModel):
    def __init__(self, sensor_type, **kwargs):
        self.sensor_type = sensor_type  # A list of strings
        # set other parameters here

    def PY(self, t, x):
        if self.sensor_times[t] == 'foo':
            return Foo(x)
        elif self.sensor_type[t] == 'bar':
            return Bar(x)
        else:
            raise ValueError('not a known sensor')

```
Basically, the distribution of Y_t given X_t=x depends wether time t is a time where you observe sensor foo, or sensor bar. 
You may also want to have a look at the following notebook:
<https://particles-sequential-monte-carlo-in-python.readthedocs.io/en/latest/notebooks/complicated_state_space_models.html>
which gives more general guidance on how to define complicated state-space models (but to be fair, it does not cover specifically this case). 

Hope this helps.

**Comment by tsbertalan** [comment]
I guess I could use that in an online situation by having some attribute of YourModel that tracks which times go to which sensor types, and updating that before I inform particles about the new measurement and let it update its belief.

 

(I considered also solving this with the multivariate with missing example <https://particles-sequential-monte-carlo-in-python.readthedocs.io/en/latest/notebooks/complicated_state_space_models.html#Multivariate-observations-with-missing-data>  from the page you linked, but this requires including the missingness in the distribution. I don’t really have this information, and anyway this seems mathematically wrong, so I still think using special times is a better approach.)

 

How do I run incrementally online, one measurement at a time?
