### ISSUE TITLE
How to use this module to implement Particle Metropolis Hastings?

### ISSUE THREAD

**Issue by williamzhao1999** [nchopin/particles#82]
How to use this module to implement Particle Metropolis Hastings?

Can you give me an example of it please?

**Comment by nchopin** [comment]
See second section of this tutorial from the documentation:
https://particles-sequential-monte-carlo-in-python.readthedocs.io/en/latest/notebooks/Bayes_estimation_ssm.html

**Comment by williamzhao1999** [comment]
Thank you, I saw particle marginal metropolis Hastings, I can't see a method for particle metropolis Hastings

**Comment by nchopin** [comment]
What do you mean by "Particle MH"? In the Holenstein et al paper, they talk about PIMH="particle independent Metropolis-Hastings", PMMH = P marginal MH", and Particle Gibbs ? Maybe you mean PIMH ?

**Comment by williamzhao1999** [comment]
Particle Metropolis Hastings: https://arxiv.org/pdf/1511.01707.pdf

**Comment by nchopin** [comment]
What they call PMH in that paper is PMMH, it's the same algorithm.

**Comment by williamzhao1999** [comment]
Ah ok thank you very much, sorry for this
