### ISSUE TITLE
MvNormal() does not properly handle default parameters

### ISSUE THREAD

**Issue by MercuryBench** [nchopin/particles#97]
Reproducible example:
`dists.MvNormal()`

returns the error message
 ```
self.cov = np.eye(loc.shape[-1]) if cov is None else cov
AttributeError: 'float' object has no attribute 'shape'
```

Reason: In definition and constructor of MvNormal,
def __init__(self, **loc=0.0**, scale=1.0, cov=None):
        self.loc = loc
        self.scale = scale
        self.cov = np.eye(**loc.shape[-1]**) if cov is None else cov

loc is both a float by default and loc.shape is called if cov is None.

**Comment by nchopin** [comment]
I am sorry, but things work as expected, you need to specify the dimension in some way. If you call 
```dists.MvNormal()```

the corresponding class has no way of determining whether you want $d=2$,  $d=17$, or something else. It should not default to a univariate Gaussian, for this you should use the dedicated class, `dists.Normal`.
